### ISSUE TITLE
Markbot Issue

### ISSUE THREAD

**Issue by faithebert** [faithebert/hear-me-oh-content#1]
<img width="785" alt="Screen Shot 2020-09-28 at 8 32 10 AM" src="https://user-images.githubusercontent.com/55109632/94432797-48d25280-0165-11eb-8e90-9833614b8a34.png">

Markbot is giving me trouble, I have been trying all weekend to appease this issue. I have tried removing that last link, changing all the different aria labels and the actual text in the <a> tag. 

@hellachella @HannahDelaney

**Comment by hellachella** [comment]
Taking a look.

**Comment by hellachella** [comment]
I think it might be hung up on the fact that your links are going to a blank hashtag rather than internal linking (in the nav). It isn't very clear in Markbot, but your menu should jump you down to the matching id. try this:

```
  <header role="banner">
    <h1>The Mighty Sloth</h1>
    <img src="images/logo.svg" alt="" role="presentation">
    <nav role="navigation">
      <ol>
        <li><a href="#sloths">Sloths</a></li>. <!-- menu links to section with id #sloths -->
        <li><a href="#three-toed-sloths">Three-toed sloths</a></li> <!-- menu links to section with id #three-toed-sloths -->
      </ol>
    </nav>
  </header>
```

**Comment by faithebert** [comment]
I just tried that and it still comes up with the same exact error. I thought maybe it was the duplicate link to the same sloth page twice on the page but removing that last link still doesn't fix it either.

**Comment by hellachella** [comment]
Line 26 +

```
<img src="images/creatures.jpg" alt="An illustration of a three-toed sloth featured with an ant-eater, a platypus & armadillos.">
```

Try aria-details on these images instead of an alt. 

```
<img src="images/creatures.jpg" alt="" aria-details="creature-caption">

```

**Comment by faithebert** [comment]
Markbot still has that error

**Comment by HannahDelaney** [comment]
I'll check and see if I can find something. This is a nit-picky one!

**Comment by hellachella** [comment]
Yeah, this is bizarre. My Monday am brain is not picking up what's wrong. It looks fine. I'm going to have a final look.

**Comment by HannahDelaney** [comment]
Soooooooo yup a very small thing. Your closing tags for the `<a>` in the nav is on the wrong side of the word "Sloths" and "Three-toed sloths".

It's messing with your accessibility because the `<a>` label isn't listed right so maybe it's trying to pick up what should be part of the button as an alt or something? More likely, Markbot is just registering an error it can't identify so is giving an error it understands.

**Comment by HannahDelaney** [comment]
You have:
```
        <li><a href="#sloths"></a>Sloths</li>
        <li><a href="#three-toed"></a>Three-toed sloths</li>
```

Change it to:
```
        <li><a href="#sloths">Sloths</a></li>
        <li><a href="#three-toed">Three-toed sloths</a></li>
```

**Comment by hellachella** [comment]
OMG ^^^^

**Comment by faithebert** [comment]
Omg thank you so so much! lol I have stared at this for so long I cant believe I didnt see that

**Comment by HannahDelaney** [comment]
Hiding in plain sight! We were all looking at the aria-labels etc ha ha

Take that Markbot!

**Comment by hellachella** [comment]
Woop woop. Thanks Hannah.

**Comment by faithebert** [comment]
Thank you guys!!
